var times = [
  {
    id: 1,
    escudo: "../img/america-mineiro.png",
    nome: "América Mineiro",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 2,
    escudo: "../img/athletico-paranaense.png",
    nome: "Athletico Paranaense",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 3,
    escudo: "../img/atletico-mineiro.png",
    nome: "Atlético Mineiro",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 4,
    escudo: "../img/bahia.png",
    nome: "Bahia",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 5,
    escudo: "../img/botafogo.png",
    nome: "Botafogo",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 6,
    escudo: "../img/corinthians.png",
    nome: "Corinthians",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 7,
    escudo: "../img/coritiba.png",
    nome: "Coritiba",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 8,
    escudo: "../img/cruzeiro.png",
    nome: "Cruzeiro",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 9,
    escudo: "../img/cuiaba.png",
    nome: "Cuiabá",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 10,
    escudo: "../img/flamengo.png",
    nome: "Flamengo",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 11,
    escudo: "../img/fluminense.png",
    nome: "Fluminense",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 12,
    escudo: "../img/fortaleza.png",
    nome: "Fortaleza",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 13,
    escudo: "../img/goias-esporte-clube.png",
    nome: "Goiás Esporte Clube",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 14,
    escudo: "../img/gremio.png",
    nome: "Grêmio",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 15,
    escudo: "../img/internacional.png",
    nome: "Internacional",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 16,
    escudo: "../img/palmeiras.png",
    nome: "Palmeiras",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 17,
    escudo: "../img/red-bull-bragantino.png",
    nome: "Red Bull Bragantino",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 18,
    escudo: "../img/santos.png",
    nome: "Santos",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 19,
    escudo: "../img/sao-paulo.png",
    nome: "São Paulo",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
  {
    id: 20,
    escudo: "../img/vasco-da-gama.png",
    nome: "Vasco",
    pontos: 0,
    partidas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
];


var ids = times.map((time) => time.id);
console.log(ids);


function jogos(times) {
  let tmp;
  let randomNumber;

  for (let i = 20; i; ) {
    randomNumber = (Math.random() * i--) | 0;
    tmp = times[randomNumber];
    times[randomNumber] = times[i];
    times[i] = tmp;
    //console.log(times[i]);
  }

}


